title:             Read. Grow. Prosper.
email:             your-email@example.com
description:
author:            Read. Grow. Prosper.
baseurl:           ""
url:               "https://use-n-delete.github.io"

# Social Profiles
twitter_username: readgrowprosper
github_username:
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
